### ISSUE TITLE
Probable solution for flickering...

### ISSUE THREAD

**Issue by ksanislo** [Pirater12/imgurup-3ds#1]
It looks like you're flushing the buffer before you swap them around, which as I remember is a mistake in one of the examples. I believe you don't even need to flush the buffer, but it's been a while since I played with this part of things...

https://github.com/Pirater12/imgurup-3ds/blob/master/source/main.c#L270

**Comment by psidex** [comment]
Dev of the file browser here, just tried it and that didn't help with the flickering :(

**Comment by ksanislo** [comment]
Are you sure you've got double buffering enabled? I don't see it turned on in the source on github (though I could be overlooking it). But it would make sense that it's not, since flushing then flipping with double buffer enabled would have always presented a blanked out buffer to the display.

I'm 90% sure this is what's behind the problem, as I remember fighting with this in my apps a year ago due to poor examples on how it should be done.

**Comment by psidex** [comment]
TBH I don't know much about the gfx side of things, I just copied what is used in the examples. Could you go into a little more detail of how to implement your idea?

**Comment by ksanislo** [comment]
The use of consoleInit() sets the buffer to single, so everything must write to the screen as it displays, causing flicker. You can manually switch it back, look in the ctrulib source for that consoleInit() function to see how it's done. Once you're in double buffer mode, you need to call the swap function to change between the one you're drawing in and the one you're presenting to the user. The flush call is basically a clear screen command, and you should use it before drawing, if you genuinely need the screen cleared of old data first. If you do a full redraw then it's unnessicary to clear the buffers first.

**Comment by psidex** [comment]
Ok, thank you, that was a good explanation :)

My question still remains though, how exactly do I implement this into my code? How do I set it to double buffer mode? What do I change? Do I need to remove any code?

Also, I re-init the console to clear it, would this not cause some flickering anyway? I can't use consoleclear() because it clears both screens, and they need to be cleared, otherwise the console scrolls down.

**Comment by hax0kartik** [comment]
Afaik, You should use consoleSelect() first and than consoleClear() to prevent both consoles from getting cleared

**Comment by psidex** [comment]
I don't think it would really make a difference though? after all, it is still clearing the screen

**Comment by ksanislo** [comment]
@thatguywiththatname After you call consoleInit(), make a call to gfxSetDoubleBuffering(GFX_TOP, true); or GFX-BOTTOM, it takes the same parameters as consoleInit() did.

This will switch you back to double buffered mode, then any graphics changes you make will be done behind the scenes, and you'll have to call gfxSwapBuffers(); in order to see that new frame buffer when you're ready to display it. 

edit: You might want to gspWaitForVBlank(); first, so you don't get tearing if the buffers are changed halfway through being drawn out to the screen as well.

**Comment by psidex** [comment]
I'm not sure if I am doing this right, I just added `gfxSetDoubleBuffering` calls after my `consoleInit` calls, and commented out `gfxFlushBuffers()`, this does not fix the flickering and causes the lower screen to constantly flicker on and off...

**Comment by ksanislo** [comment]
@thatguywiththatname That sounds to me like you've got more than one swap buffers call, and your second buffer isn't being drawn in before it gets swapped again.

**Comment by hax0kartik** [comment]
Uh this is a stuid question but @thatguywiththatname did you use gspWaitForVBlank() and gfxSwapBuffers() ?

**Comment by psidex** [comment]
@ksanislo I have only ever had one swap buffer call.
@Pirater12 Yep

I honestly have no idea how to do this stuff, you can see all my code [here](https://github.com/thatguywiththatname/3DES), specifically the [`main`](https://github.com/thatguywiththatname/3DES/blob/master/source/main.c) file and the [`draw`](https://github.com/thatguywiththatname/3DES/blob/master/source/draw.c) file will have what you are both talking about in, maybe you guys can see something i'm missing?

**Comment by ksanislo** [comment]
@thatguywiththatname you've got a second consoleInit() in https://github.com/thatguywiththatname/3DES/blob/master/source/draw.c#L12 

Which will likely be putting you back into to single buffer mode. It might be best to try to move all of the init type stuff up to the top of main() and make sure you don't touch it anywhere else...

**Comment by psidex** [comment]
@ksanislo If I do move it, how can I clear just the top screen? Consoleclear() only ever clears both screens

**Comment by ksanislo** [comment]
You can zero the buffer via any method you'd like, even something as simple as memset(screenpointer, 0, 240 * 400 * 2); The size is 2 bytes per pixel (16 bit color is what consoleInit() sets up, it can be different), for the total pixel count of the screen...

There's probably a ctrulib call which does the same thing, that can be pointed per screen specifically... but I don't know what it would be off the top of my head.

**Comment by ksanislo** [comment]
@thatguywiththatname Actually... Here's what you're looking for:

https://github.com/smealum/ctrulib/blob/master/libctru/source/console.c#L75

Looks like it clears out the currently specified console you're using, either top or bottom.

**Comment by psidex** [comment]
@ksanislo 

```c
warning: implicit declaration of function 'consoleCls' [-Wimplicit-function-declaration]
     consoleCls(&topScreen);
```

It doesen't seem to actually be in libctru?

**Comment by ksanislo** [comment]
@thatguywiththatname are you sure you're using the current version of ctrulib? You might want to grab the latest repo via git and reinstall that one.

edit: actually, never mind, it's not defined in the .h include file, so you'd have to define it yourself if you want to use it once linked against it. It seems like you might just as easily be able to print out the ANSI clear screen code and have it do the right thing as well... ^[[2J should do it (where ^[ is the single escape character... aka \x1b )

**Comment by psidex** [comment]
@ksanislo so `\x1b[2J` ?

**Comment by hax0kartik** [comment]
@thatguywiththatname That won't work.Check discord.

**Comment by psidex** [comment]
@Pirater12 Can't get on it till later. Can you write it here?

**Comment by hax0kartik** [comment]
I got it to work without flashing...
https://www.youtube.com/watch?v=wGh7tVnpvM4
without enabling doublebuffer or removing flash calls.
`printf("\x1b[0;0H` and a custom dir_draw function was needed.
_Scrolling does not work still and requires some work_

**Comment by Pirater12** [comment]
#b5abd9122bcc744e2d6846eaec89f44799f19a80

**Comment by hax0kartik** [comment]
Fixed with commit:https://github.com/Pirater12/imgurup-3ds/commit/b5abd9122bcc744e2d6846eaec89f44799f19a80 , https://github.com/Pirater12/imgurup-3ds/commit/768a5104b9fd59e19c8a51c56b596fae7409e220 and https://github.com/Pirater12/imgurup-3ds/commit/f93e044f7b38a012bd8a852cd9d060808611b42d
